name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ["mkdocs_test"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Setup Pages
      #  uses: actions/configure-pages@v3

      # build env setup
      - name: Install Graphviz
        run: |
          sudo apt update
          sudo apt install graphviz
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Check poetry
        run: |
          poetry --version
          poetry config --list
      - name: Install dependencies
        run: poetry install --no-root
      - name: Deploy GH Pages
        run: |
          poetry run mkdocs gh-deploy --force